### ISSUE TITLE
Can't use without a default file

### ISSUE THREAD

**Issue by scottsandersdev** [kerimdzhanov/dotenv-flow#1]
Currently we can't solely rely on `.env.{NODE_ENV}` files, we also need a default `.env` file. On my current project, there are no values that are default values. That would be understandable if my `.env.{NODE_ENV} files` were overriding the default values, but that isn't happening. So I end up needing to commit a blank `.env` file. 

Would be nice to add functionality to -  
1. not require a default `.env` file (projects without this will throw an error - `Error: ENOENT: no such file or directory, open '/Users/ssanders/dev/project/skii/middleware/.env'`)
2. make sure that the files with NODE_ENV vars override the defaults

**Comment by kerimdzhanov** [comment]
Thanks for reporting this!
