### ISSUE TITLE
version bump to major

### ISSUE THREAD

**Issue by crobinson42** [kerimdzhanov/dotenv-flow#14]
Because of semver and npm versioning pattern, the current version in a projects package.json of `dotenv-flow: ^0.4.0` will install any package up to and including `1.x.x` - so, if the library maintainers of this repo decide to bump a major version to `1.0.0` with breaking changes and all the projects out there aren't aware and they are using the carrot in their dependencies list for this package, their project will install the breaking change.

I recommend bumping to 1.0.0 and publishing to set the baseline for this package.

**Comment by kerimdzhanov** [comment]
Absolutely agree,

I recently realized that I've released breaking changes as a minor version bump. I'm sorry, my bad...

Currently the only dependency "dotenv" is updated up to `v8.0.0` where they're dropped the support of Node.js v6, and it is also a breaking change that I'm planning to release as `dotenv-flow@v1.0.0`.

Anyway, thanks for your recommendation! I appreciate it 👍

**Comment by crobinson42** [comment]
Just to be clear that the point is getting across, you **should not release breaking changes on v1.0.0** because of the way that npm version resolution with the carrot in "^0.4.0" works - that will also install v1.0.0 if it's published. I'm saying you should arbitrarily release v1.0.0 _today_ and then when you have breaking changes in the future you're next major will be v2.0.0.

**Comment by kerimdzhanov** [comment]
Ahh... Ok, now it's clear. I will release `v1.0.0` without any breaking changes, then _right after_ I will release `v2.0.0` with breaking changes. Thanks! I didn't know about this subtlety.
