### ISSUE TITLE
How to disable logs about already defined env

### ISSUE THREAD

**Issue by vimutti77** [kerimdzhanov/dotenv-flow#17]
When I run my production app with docker `docker run -e foo=1 -e bar=2 myapp` always get the logs about already defined env like this
```
dotenv-flow: "foo" is already defined in `process.env` and will not be overwritten
dotenv-flow: "bar" is already defined in `process.env` and will not be overwritten
```
How can I disable these log.

**Comment by kerimdzhanov** [comment]
Nice remark 👍, it seems that we need to add the `silent` option.

**Comment by anandchapter247** [comment]
@kerimdzhanov Any planning update this in near future?

**Comment by kerimdzhanov** [comment]
@anandchapter247, the [`silent` option](https://github.com/kerimdzhanov/dotenv-flow#optionssilent) is already implemented in [v3.1.0](https://github.com/kerimdzhanov/dotenv-flow/blob/master/CHANGELOG.md#310-2019-08-17). You just need to update.

**Comment by metaskills** [comment]
How is that supposed to be used ES modules?

**Comment by metaskills** [comment]
Seems like this:

```javascript
import { config } from "dotenv-flow";
config({ silent: true });
```

**Comment by kerimdzhanov** [comment]
Hi @metaskills,

Yup, that should work starting from dotenv-flow v3.3.0.

Alternatively, this also works:

```ts
import dotenvFlow from 'dotenv-flow';
dotenvFlow.config({ silent: true });
```

Or upgrade to dotenv-flow v4 where this message is moved to debug logs which are disabled by default and can be enabled via `{ debug: true }`.
