### ISSUE TITLE
    default_node_env: 'production' ignored

### ISSUE THREAD

**Issue by neuronflow** [kerimdzhanov/dotenv-flow#25]
I start my script with:
```
require('dotenv-flow').config({
    default_node_env: 'production'
});
```

The default_node_env is ignored. NODE_ENV is not set.
Ubuntu 1804
node 13.7.0

**Comment by kerimdzhanov** [comment]
The module doesn't set `process.env.NODE_ENV` variable. It just loads environment variables from the `.env.production` file.

**Comment by kerimdzhanov** [comment]
Take a look at [this comment](https://github.com/kerimdzhanov/dotenv-flow/issues/13#issuecomment-490574452) from issue #13, I've described here why.
