### ISSUE TITLE
Great work ✨

### ISSUE THREAD

**Issue by aaronransley** [kerimdzhanov/dotenv-flow#3]
This is a wonderful package doing _just_ what I was looking for. Thank you for putting this together!

🍻

**Comment by pedrovagner** [comment]
Unfortunately, **GitHub** doesn't have a section to post things like this. Soon, this issue will be closed and forgot forever :(

**Comment by kerimdzhanov** [comment]
@aaronransley, I'm very glad to know that it's helpful! Appreciate your participation guys!
🍻
