### ISSUE TITLE
Is this the 12 factor way?

### ISSUE THREAD

**Issue by reergymerej** [kerimdzhanov/dotenv-flow#35]
The way I read this, it seems merging multiple env vars is contrary to the Twelve-Factor App.

https://12factor.net/config
> In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars. They are never grouped together as “environments”, but instead are independently managed for each deploy. 

Can someone please enlighten me?

**Comment by kerimdzhanov** [comment]
Hey @reergymerej,

Good point, I understood that the headline in "README" might be really confusing.

Actually, all the environment variables defined in `.env*` files are considered as "defaults" for your application and tracked by VCS to make your app "just work" after cloning the repo without any environment variables predefined in your local environment. But if you need to reconfigure some of them for some specific needs just create `.env.local` or `.env.development.local` and overwrite them there. Or simply define them in your OS environment like `export ENV_VAR=value` if you don't want to have "grouping" feature at all.

Regarding the twelve-factor's "_independently managing for each deploy_", this library allows having `.env.production.local` _(that shouldn't be tracked by VCS)_ for each production machine, and can be managed separately. It's, actually, almost the same as configuring your environment variables in files like `~/.bash_profile`, `/etc/profile.d/*`, etc. locally for each production machine. So, it's up to you where do you want to store your application environment configuration and whether you need to have "grouped" environment variables.

Also, to make it clear, there are no predefined groups like "development", "test", and "production". You may not use them at all, just having `.env` _(tracked to keep defaults)_ and `.env.local` _(untracked to rewrite default configuration for local needs)_.

P.S.
If you still think that the headline section in "README" is confusing, please suggest your option. I would be glad to make it better.

**Comment by reergymerej** [comment]
@kerimdzhanov thanks for the thoughtful response.  I see what you're saying. 👍
