### ISSUE TITLE
Using wrong .env file for specified NODE_ENV

### ISSUE THREAD

**Issue by jfuehner** [kerimdzhanov/dotenv-flow#4]
I'm running into an issue using dotenv-flow version 0.1.0. I have a npm build script that sets the NODE_ENV environment variable using cross-env. For example,

`cross-env NODE_ENV=development npm run build`

In my root directory I have the following .env files...

- .env.development
- .env.test
- .env.production

When I run my script I can see the NODE_ENV as being set to the correct environment (i.e., development, test, production). At the start of the build `require('dotenv-flow').config()` is called.

However, when I log one of the environment variables that is defined in all three of the files I am getting back the value from the .env.production file even though NODE_ENV is specified as **development**.

Seems like dotenv-flow is not respecting the NODE_ENV variable value. Any ideas?

**Comment by Asuza** [comment]
@jfuehner did you solve this issue? I think I'm stuck in the same boat.

**Comment by kerimdzhanov** [comment]
Hope this might be helpful:

**dotenv-flow** does it as simple as:

https://github.com/kerimdzhanov/dotenv-flow/blob/80ff430783fcf7e76c4ecdd58be0965efd1bf94a/lib/dotenv-flow.js#L130

So, by priority: `options.node_env`, if not defined then `process.env.NODE_ENV`, and if none of them is defined then `options.default_node_env`.
