### ISSUE TITLE
Empty values aren't respected

### ISSUE THREAD

**Issue by pr4th4m** [kerimdzhanov/dotenv-flow#42]
Setting env var with empty value isn't set as env var
```
# .env  file
MYVAR=
```
Output
```
process.env["MYVAR"]                                                                                              
undefined
```
However, https://github.com/motdotla/dotenv seems to set env var with empty values just fine

**Comment by kerimdzhanov** [comment]
Yep! Thanks for reporting.

**Comment by kerimdzhanov** [comment]
As for August 2023, I couldn't reproduce the issue.

Given that the parsing part is done by the "dotenv" itself (since we use it as a dependency) after some update the bug is gone.
