### ISSUE TITLE
cannot use base64 encoded .env file to decode

### ISSUE THREAD

**Issue by akshay-mahakalkar** [kerimdzhanov/dotenv-flow#45]
I have tried mentioning option {encoding: 'base64'}. But its actually reading and then encoding to base64.
As per me possible behavior should be if a base64 encoded .env file is passed then package should decode it from base64 and then load in process.env in nodejs program.

If the current behavior is not and bug and is expected one then is there any way that I can read base64 encoded .env file and get decoded environment variables in process.env?

**Comment by kerimdzhanov** [comment]
Hey @akshay-mahakalkar,

Any updates on this issue?
