### ISSUE TITLE
[pre-pull request] --mode switch

### ISSUE THREAD

**Issue by solaris765** [kerimdzhanov/dotenv-flow#5]
I didn't know where to put this and I didn't want to submit a pull request for unfinished / possibly unwanted additions.

BUT

I forked and added a --mode switch that gets parsed during the 'getDotenvFilenames' Fn that should make your module treat .env files the same as vue-cli. (this was more convenient for my team) 

Basically if the switch exists it looks for .env.{mode} or .env.{mode}.local files instead of NODE_ENV files, though it will still default to using NODE_ENV as the mode.

```
function getDotenvFilenames(cwd) {
  const { NODE_ENV = 'development' } = process.env;

  let modeI = process.argv.indexOf("--mode")
  let mode = (modeI != -1 && process.argv.length > modeI + 1) ?
    process.argv[modeI + 1] :
    NODE_ENV

  return [
    NODE_ENV && `${cwd}/.env.${mode}.local`,
    NODE_ENV && `${cwd}/.env.${mode}`,
    NODE_ENV !== 'test' && `${cwd}/.env.local`,
    `${cwd}/.env`
  ].filter(filename => filename && fs.existsSync(filename));
}
```

If this seems like an addition that would fit I'll write up some actual testing cases before submitting a pull request.

(if you look in my fork you will also notice that I changed NODE_ENV to default to 'development', I don't plan on including this in a possible pull request.)

**Comment by kerimdzhanov** [comment]
I would also like to suggest you to use something like [commander.js](https://github.com/tj/commander.js) to parse CLI options, `process.argv[i + 1]` is not really a good way ;).

**Comment by solaris765** [comment]
Ah. That makes sense. And thanks for the tip on Cammander.js, I hadn't seen that.

The main reason I decided to keep NODE_ENV and mode separate was because in our use case NODE_ENV is used inside the program to differentiate production vs development or whatever. 

And .env files seemed like a good option to start storing those sorts of configurations in a central morning manageable location.  Though I see now it may have been better to use one or the other and not get stuck between both like I have.

Thank you very much for the input and your work on this tool!

Really it helped a lot!

**Comment by kerimdzhanov** [comment]
Ok, I understand.

We can have "environment" as a configuration option, something like:

```js
require('dotenv-flow').config({
  env: process.env.NODE_ENV // by default
});
```

Thus you can provide your own value and make it independent of `process.env.NODE_ENV` at all.

**Comment by kerimdzhanov** [comment]
I will add this option in the next release.

**Comment by solaris765** [comment]
Awesome. Keep up the great work!
