### ISSUE TITLE
how to load with import?

### ISSUE THREAD

**Issue by ralyodio** [kerimdzhanov/dotenv-flow#56]
Is this correct?

```
import cfg from 'dotenv-flow';

cfg.config();
```

**Comment by lucsky** [comment]
Using the same way as documented for `dotenv` (see [here](https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import)) seems to work just fine:

```js
// As early as possible
import 'dotenv-flow/config';
```

**Comment by perrin4869** [comment]
@lucsky that wouldn't work unless https://github.com/kerimdzhanov/dotenv-flow/pull/57 is merged

**Comment by lucsky** [comment]
@perrin4869 weird, I guess I'm lucky then because it works perfectly fine for me in two different projects... 🤔

**Comment by perrin4869** [comment]
Do you have type module in package.json?

**Comment by kachkaev** [comment]
This worked for me in a ESM file:

```
import { foo } from "foo";
import { bar } from "./path/to/bar";

(await import("dotenv-flow")).config();
```

This requires top-level await.

Because static imports are async by nature, I’m not sure if placing `await` before imports will guarantee correct `process.env` values in other imports. Needs checking.

**Comment by MastaAaron** [comment]
FWIW: even though #57 hasn't been merged, I've had luck using this within an ES module:

```js
import "dotenv-flow/config.js";
```

The `".js"` is necessary because of [this](https://nodejs.org/api/esm.html#import-specifiers) (see 2nd and 3rd bullet points). One of those tricky/annoying differences with ES modules in a pure Node context versus the Webpack context many of us are more familiar with.

I'm also able to get @kachkaev's method to work, but other imported module files are only able to access the vars if they're imported *after* dotenv and also use dynamic `import()`:

```js
// probably doesn't matter where this goes since it's a package and doesn't use process.env internally
const foo = await import("foo");

(await import("dotenv-flow")).config(); // has to come before the import below
const bar = await import("./path/to/bar.js"); // process.env used in this file
```

**Comment by qiulang** [comment]
I think this is because nodejs support that, check https://nodejs.org/api/esm.html#commonjs-namespaces

> When importing a CommonJS module, it can be reliably imported using the ES module default import or its corresponding sugar syntax:

**Comment by waynebloss** [comment]
My `config/env.ts` file doesn't import anything else so this works for me to set the default `NODE_ENV` in an ESM package (with `"type": "module" in package.json):

```ts
if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = "development";
}
(await import("dotenv-flow")).config();
```

However the following would not work in an ESM package:

```ts
(await import("dotenv-flow")).config({
  node_env: process.env.NODE_ENV,
  default_node_env: "development",
});
```

**Comment by kerimdzhanov** [comment]
Hello gents,

Sorry for being late to the party 😅,

Let me check #57 by @perrin4869 (thanks a lot for the PR!), for now, you can try this:

```ts
import * as dotenvFlow from 'dotenv-flow';
dotenvFlow.config();
```

I'll update the README appropriately once we check and merge the PR (`* as` may not be needed after merging).
