### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by aymericbouzy** [kerimdzhanov/dotenv-flow#58]
If you need help maintaining this package, please ask, a few PRs have been left un-answered for a while. Thanks 🙏

**Comment by bartvanandel** [comment]
@kerimdzhanov Would you be so kind to reply?

**Comment by JLAcostaEC** [comment]
Apparently @kerimdzhanov is not active, if you see his profile only has 1 commit in a year, therefore I would take this repository as abandoned.

**Comment by piotr-cz** [comment]
Are you guys using any alternatives?

**Comment by qiulang** [comment]
Hi, I did some research and find this one https://github.com/entropitor/dotenv-cli  but I am still learning it.

**Comment by piotr-cz** [comment]
ATM only thing I'm missing are updated dependencies.
Particularly `dotenv >= 15.0.0` with support of *Multiline values*

**Comment by qiulang** [comment]
@piotr-cz what is ATM ?

**Comment by piotr-cz** [comment]
I'm using this package together with [mikro-orm](https://mikro-orm.io/) which has `dotenv` in it's dependencies, so I decided for an override in package.json to use same version:

```jsonc
  // package.json
  "dependencies": {
    "dotenv-flow": "^3.2.0"
  },
  "overrides": {
    "dotenv-flow@^3.2.0": {
      "dotenv": ">= 15.0.0"
    }
  }
```

**Comment by kerimdzhanov** [comment]
Hello gets,

Sorry for the late reply. Yes, the package is maintained 😅

I'll take a look at what's new in "moldotla/dotenv" since v8.0.0. and release a new version once I make sure that everything is ok.

Thanks for being patient all this time 🙏

**Comment by justin-hackin** [comment]
> Hi, I did some research and find this one https://github.com/entropitor/dotenv-cli but I am still learning it. But its usage is not exactly the same.

I was looking for an alternative to dotenv-cli that supports nested configs but I didn't realize dotenv-cli has a `-c` (cascade) flag that will provide the functionality described in this repository. This library seems to be the industry-standard way of working with .env files from a CLI. Maybe this library should be put to rest?
