### ISSUE TITLE
Filename extension

### ISSUE THREAD

**Issue by raychz** [kerimdzhanov/dotenv-flow#7]
I think this way of organizing environment-dependent variables has a ton of potential!  One small nitpick, however, is that I've now lost support for .env file syntax highlighting on my IDE.  If the file name structure was "flipped" and looked more like `local.production.env`, this wouldn't be an issue.  There are probably complexities that I'm overlooking, but would this be possible?

**Comment by gaurav-** [comment]
Doesn't the IDE support patterns for file extensions? Then could configure it for a pattern like `.env*`. I know IntelliJ IDEA which supports such configuration

**Comment by raychz** [comment]
Thanks @gaurav-!
