### ISSUE TITLE
.env subfolders

### ISSUE THREAD

**Issue by raychz** [kerimdzhanov/dotenv-flow#8]
In my project's root, I have a `.env` folder where I store my `.env.<environment>` and `.env.<environment>.local` files.  This works great when I pass the `{ cwd: '.env/' }` option to `config`, but I'd like to have subfolders under `.env` that would hold each pair of environment files.  

For example:
```
.env/
-----.env
-----.env.local
-----development/
----------.env.development
----------.env.development.local
-----staging/
----------.env.staging
----------.env.staging.local
-----production/
----------.env.production
----------.env.production.local
```

Changing the `cwd` option to `.env/*` or `.env/**/*` doesn't seem to work and my project fails to recognize variables not in `.env` or `.env.local`.  Any ideas?

**Comment by kerimdzhanov** [comment]
I think it's possible to implement this feature to work using the path template. It would look like:

```js
require('dotenv-flow').config({
  path: './.env/${NODE_ENV}/.env.${NODE_ENV}?(.local)'
});
```

The same approach applies to #7. For that example, it would look like:

```js
require('dotenv-flow').config({
  path: './?(local.)${NODE_ENV}.env'
});
```

As you can understand this is not supported by the module at the time, so your PR's are very welcome!

**Comment by viveksharmaui** [comment]
Can i send PR on this issue i'm currently understanding the codebase after that i will send PR .

**Comment by kerimdzhanov** [comment]
Hello gentlemen,

With the new `pattern` option this particular case will become as easy as:

```js
require('dotenv-flow').config({
  pattern: '.env/[node_env/].env[.node_env][.local]'
});
```

This feature is going to be released with dotenv-flow `v4.x`.
